### ISSUE TITLE
Random issue

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/dash#361]
Last message: :tick
2020-02-28T00:42:23.078608041Z app[web.1]: 00:42:23.078 [error] GenServer #PID<0.18745.0> terminating
2020-02-28T00:42:23.078685103Z app[web.1]: ** (FunctionClauseError) no function clause matching in Float.round/2
2020-02-28T00:42:23.078695635Z app[web.1]:     (elixir 1.10.0) lib/float.ex:259: Float.round(60, 2)
2020-02-28T00:42:23.078703300Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/time.ex:25: anonymous fn/2 in Dash.Api.Harvest.Time.add_hours_per_day/1
2020-02-28T00:42:23.078711079Z app[web.1]:     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
2020-02-28T00:42:23.078718695Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/time.ex:24: Dash.Api.Harvest.Time.add_hours_per_day/1
2020-02-28T00:42:23.078726017Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest.ex:14: Dash.Api.Harvest.get/1
2020-02-28T00:42:23.078733198Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/requester.ex:29: Dash.Api.Harvest.Requester.handle_info/2
2020-02-28T00:42:23.078740316Z app[web.1]:     (stdlib 3.10) gen_server.erl:637: :gen_server.try_dispatch/4
2020-02-28T00:42:23.078747478Z app[web.1]:     (stdlib 3.10) gen_server.erl:711: :gen_server.handle_msg/6
2020-02-28T00:42:23.078754750Z app[web.1]: Last message: :tick
2020-02-28T00:42:24.928662492Z app[web.1]: 00:42:24.928 [error] GenServer #PID<0.18754.0> terminating
2020-02-28T00:42:24.928716643Z app[web.1]: ** (FunctionClauseError) no function clause matching in Float.round/2
2020-02-28T00:42:24.928726675Z app[web.1]:     (elixir 1.10.0) lib/float.ex:259: Float.round(60, 2)
2020-02-28T00:42:24.928734634Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/time.ex:25: anonymous fn/2 in Dash.Api.Harvest.Time.add_hours_per_day/1
2020-02-28T00:42:24.928742553Z app[web.1]:     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
2020-02-28T00:42:24.928750316Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/time.ex:24: Dash.Api.Harvest.Time.add_hours_per_day/1
2020-02-28T00:42:24.928757667Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest.ex:14: Dash.Api.Harvest.get/1
2020-02-28T00:42:24.928764932Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/requester.ex:29: Dash.Api.Harvest.Requester.handle_info/2
2020-02-28T00:42:24.928772234Z app[web.1]:     (stdlib 3.10) gen_server.erl:637: :gen_server.try_dispatch/4
2020-02-28T00:42:24.928779398Z app[web.1]:     (stdlib 3.10) gen_server.erl:711: :gen_server.handle_msg/6
2020-02-28T00:42:24.928786640Z app[web.1]: Last message: :tick
2020-02-28T00:42:26.572638015Z app[web.1]: 00:42:26.570 [error] GenServer #PID<0.18763.0> terminating
2020-02-28T00:42:26.572692448Z app[web.1]: ** (FunctionClauseError) no function clause matching in Float.round/2
2020-02-28T00:42:26.572702386Z app[web.1]:     (elixir 1.10.0) lib/float.ex:259: Float.round(60, 2)
2020-02-28T00:42:26.572710215Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/time.ex:25: anonymous fn/2 in Dash.Api.Harvest.Time.add_hours_per_day/1
2020-02-28T00:42:26.572718204Z app[web.1]:     (elixir 1.10.0) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
2020-02-28T00:42:26.572726026Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/time.ex:24: Dash.Api.Harvest.Time.add_hours_per_day/1
2020-02-28T00:42:26.572733562Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest.ex:14: Dash.Api.Harvest.get/1
2020-02-28T00:42:26.572740897Z app[web.1]:     (dash 0.1.0) lib/dash/api/harvest/requester.ex:29: Dash.Api.Harvest.Requester.handle_info/2
2020-02-28T00:42:26.572766326Z app[web.1]:     (stdlib 3.10) gen_server.erl:637: :gen_server.try_dispatch/4
2020-02-28T00:42:26.572774569Z app[web.1]:     (stdlib 3.10) gen_server.erl:711: :gen_server.handle_msg/6
2020-02-28T00:42:26.572782188Z app[web.1]: Last message: :tick

**Comment by alanvardy** [comment]
PR up
